name: Deploy a EC2

on:
  push:
    branches:
      - main  # Cambia si usas otro branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy over SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd /var/www/ecommerce  # Reemplaza con la ruta real de tu proyecto
          git pull origin main
          composer install --no-interaction --no-dev --optimize-autoloader
          npm install
          npm run build
          php artisan migrate --force
          sudo systemctl restart nginx